# Generated by Django 2.2.1 on 2019-05-06 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(default='www.defaulturl.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heading',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings_set', to='AnalysisApplication.WebPage'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='delete_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 15, 18, 34, 711741)),
        ),
    ]
