# Generated by Django 2.2.1 on 2019-05-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalysisApplication', '0002_auto_20190506_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='delete_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 17, 59, 14, 211161)),
        ),
    ]
